// <auto-generated />
using System;
using System.Collections.Generic;
using Leadsly.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leadsly.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220817160801_RemoveContainerNameFromEcsTasks")]
    partial class RemoveContainerNameFromEcsTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Customer_StripeId")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalProvider")
                        .HasColumnType("text");

                    b.Property<string>("ExternalProviderUserId")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Customer_StripeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Campaign", b =>
                {
                    b.Property<string>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignProspectListId")
                        .HasColumnType("text");

                    b.Property<int>("CampaignType")
                        .HasColumnType("integer");

                    b.Property<long>("CreatedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyInvites")
                        .HasColumnType("integer");

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean");

                    b.Property<string>("HalId")
                        .HasColumnType("text");

                    b.Property<bool>("IsWarmUpEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("StartTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("CampaignId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CampaignProspectListId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspect", b =>
                {
                    b.Property<string>("CampaignProspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<long>("AcceptedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignProspectListId")
                        .HasColumnType("text");

                    b.Property<bool>("ConnectionSent")
                        .HasColumnType("boolean");

                    b.Property<long>("ConnectionSentTimestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("FollowUpComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("FollowUpMessageSent")
                        .HasColumnType("boolean");

                    b.Property<long>("LastFollowUpMessageSentTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryProspectId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Replied")
                        .HasColumnType("boolean");

                    b.Property<long>("RepliedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<int>("SentFollowUpMessageOrderNum")
                        .HasColumnType("integer");

                    b.HasKey("CampaignProspectId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignProspectListId");

                    b.HasIndex("PrimaryProspectId");

                    b.ToTable("CampaignProspects");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectFollowUpMessage", b =>
                {
                    b.Property<string>("CampaignProspectFollowUpMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignProspectId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("CampaignProspectFollowUpMessageId");

                    b.HasIndex("CampaignProspectId");

                    b.ToTable("CampaignProspectFollowUpMessages");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", b =>
                {
                    b.Property<string>("CampaignProspectListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryProspectListId")
                        .HasColumnType("text");

                    b.Property<string>("ProspectListName")
                        .HasColumnType("text");

                    b.HasKey("CampaignProspectListId");

                    b.HasIndex("PrimaryProspectListId");

                    b.ToTable("CampaignProspectLists");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignWarmUp", b =>
                {
                    b.Property<string>("CampaignWarmUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer");

                    b.Property<long>("StartDateTimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("CampaignWarmUpId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignWarmUps");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessage", b =>
                {
                    b.Property<string>("FollowUpMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("FollowUpMessageId");

                    b.HasIndex("CampaignId");

                    b.ToTable("FollowUpMessages");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessageDelay", b =>
                {
                    b.Property<string>("FollowUpMessageDelayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpMessageId")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("FollowUpMessageDelayId");

                    b.HasIndex("FollowUpMessageId")
                        .IsUnique();

                    b.ToTable("FollowUpMessageDelay");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessageJob", b =>
                {
                    b.Property<string>("FollowUpMessageJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignProspectId")
                        .HasColumnType("text");

                    b.Property<string>("FollowUpMessageId")
                        .HasColumnType("text");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.HasKey("FollowUpMessageJobId");

                    b.ToTable("FollowUpMessageJobs");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ChromeProfile", b =>
                {
                    b.Property<string>("ChromeProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("CampaignPhaseType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ChromeProfileId");

                    b.ToTable("ChromeProfileNames");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ConnectionWithdrawPhase", b =>
                {
                    b.Property<string>("ConnectionWithdrawPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("PageUrl")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.Property<string>("SocialAccountId")
                        .HasColumnType("text");

                    b.HasKey("ConnectionWithdrawPhaseId");

                    b.HasIndex("SocialAccountId")
                        .IsUnique();

                    b.ToTable("ConnectionWithdrawPhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.FollowUpMessagePhase", b =>
                {
                    b.Property<string>("FollowUpMessagePhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("PageUrl")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.HasKey("FollowUpMessagePhaseId");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("FollowUpMessagesPhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.MonitorForNewConnectionsPhase", b =>
                {
                    b.Property<string>("MonitorForNewConnectionsPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("PageUrl")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.Property<string>("SocialAccountId")
                        .HasColumnType("text");

                    b.HasKey("MonitorForNewConnectionsPhaseId");

                    b.HasIndex("SocialAccountId")
                        .IsUnique();

                    b.ToTable("MonitorForNewConnectionsPhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ProspectListPhase", b =>
                {
                    b.Property<string>("ProspectListPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<long>("CompletedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.Property<List<string>>("SearchUrls")
                        .HasColumnType("text[]");

                    b.HasKey("ProspectListPhaseId");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("ProspectListPhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ScanProspectsForRepliesPhase", b =>
                {
                    b.Property<string>("ScanProspectsForRepliesPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("PageUrl")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.Property<string>("SocialAccountId")
                        .HasColumnType("text");

                    b.HasKey("ScanProspectsForRepliesPhaseId");

                    b.HasIndex("SocialAccountId")
                        .IsUnique();

                    b.ToTable("ScanProspectsForRepliesPhase");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendConnectionRequestPhase", b =>
                {
                    b.Property<string>("SendConnectionRequestPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.HasKey("SendConnectionRequestPhaseId");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("SendConnectionRequestPhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendEmailInvitePhase", b =>
                {
                    b.Property<string>("SendEmailInvitePhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<int>("PhaseType")
                        .HasColumnType("integer");

                    b.HasKey("SendEmailInvitePhaseId");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("SendEmailInvitePhases");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspect", b =>
                {
                    b.Property<string>("PrimaryProspectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<long>("AddedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("EmploymentInfo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryProspectListId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("SearchResultAvatarUrl")
                        .HasColumnType("text");

                    b.HasKey("PrimaryProspectId");

                    b.HasIndex("PrimaryProspectListId");

                    b.ToTable("PrimaryProspects");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", b =>
                {
                    b.Property<string>("PrimaryProspectListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<long>("CreatedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("PrimaryProspectListId");

                    b.HasIndex("UserId");

                    b.ToTable("PrimaryProspectLists");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrl", b =>
                {
                    b.Property<string>("SearchUrlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignProspectListId")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryProspectListId")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("SearchUrlId");

                    b.HasIndex("CampaignProspectListId");

                    b.HasIndex("PrimaryProspectListId");

                    b.ToTable("SearchUrls");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrlDetails", b =>
                {
                    b.Property<string>("SearchUrlDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentUrl")
                        .HasColumnType("text");

                    b.Property<bool>("FinishedCrawling")
                        .HasColumnType("boolean");

                    b.Property<long>("LastActivityTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("text");

                    b.Property<bool>("StartedCrawling")
                        .HasColumnType("boolean");

                    b.Property<string>("WindowHandleId")
                        .HasColumnType("text");

                    b.HasKey("SearchUrlDetailsId");

                    b.HasIndex("CampaignId");

                    b.ToTable("SentConnectionsStatuses");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrlProgress", b =>
                {
                    b.Property<string>("SearchUrlProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<bool>("Exhausted")
                        .HasColumnType("boolean");

                    b.Property<long>("LastActivityTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("LastPage")
                        .HasColumnType("integer");

                    b.Property<int>("LastProcessedProspect")
                        .HasColumnType("integer");

                    b.Property<string>("SearchUrl")
                        .HasColumnType("text");

                    b.Property<bool>("StartedCrawling")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalSearchResults")
                        .HasColumnType("integer");

                    b.Property<string>("WindowHandleId")
                        .HasColumnType("text");

                    b.HasKey("SearchUrlProgressId");

                    b.HasIndex("CampaignId");

                    b.ToTable("SearchUrlsProgress");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SendConnectionsStage", b =>
                {
                    b.Property<string>("SendConnectionsStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<int>("NumOfConnections")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("StartTime")
                        .HasColumnType("text");

                    b.HasKey("SendConnectionsStageId");

                    b.HasIndex("CampaignId");

                    b.ToTable("SendConnectionsStages");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.CloudMapDiscoveryService", b =>
                {
                    b.Property<string>("CloudMapDiscoveryServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Arn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EcsServiceId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NamespaceId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceDiscoveryId")
                        .HasColumnType("text");

                    b.Property<string>("VirtualAssistantId")
                        .HasColumnType("text");

                    b.HasKey("CloudMapDiscoveryServiceId");

                    b.HasIndex("EcsServiceId")
                        .IsUnique();

                    b.HasIndex("VirtualAssistantId");

                    b.ToTable("CloudMapDiscoveryServices");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Customer_Stripe", b =>
                {
                    b.Property<string>("Customer_StripeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.HasKey("Customer_StripeId");

                    b.ToTable("StripeCustomers", (string)null);
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsService", b =>
                {
                    b.Property<string>("EcsServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ClusterArn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchedulingStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceArn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualAssistantId")
                        .HasColumnType("text");

                    b.HasKey("EcsServiceId");

                    b.HasIndex("VirtualAssistantId");

                    b.ToTable("EcsServices");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsServiceRegistry", b =>
                {
                    b.Property<string>("EcsServiceRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("EcsServiceId")
                        .HasColumnType("text");

                    b.Property<string>("RegistryArn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EcsServiceRegistryId");

                    b.HasIndex("EcsServiceId");

                    b.ToTable("EcsServiceRegistries");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsTask", b =>
                {
                    b.Property<string>("EcsTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("EcsServiceId")
                        .HasColumnType("text");

                    b.Property<string>("TaskArn")
                        .HasColumnType("text");

                    b.HasKey("EcsTaskId");

                    b.HasIndex("EcsServiceId");

                    b.ToTable("EcsTasks");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsTaskDefinition", b =>
                {
                    b.Property<string>("EcsTaskDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("TaskDefinitionArn")
                        .HasColumnType("text");

                    b.Property<string>("VirtualAssistantId")
                        .HasColumnType("text");

                    b.HasKey("EcsTaskDefinitionId");

                    b.HasIndex("VirtualAssistantId");

                    b.ToTable("EcsTaskDefinitions");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.HalUnit", b =>
                {
                    b.Property<string>("HalUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("EndHour")
                        .HasColumnType("text");

                    b.Property<string>("HalId")
                        .HasColumnType("text");

                    b.Property<string>("StartHour")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.HasKey("HalUnitId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("HalUnits");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.LeadslyTimeZone", b =>
                {
                    b.Property<string>("LeadslyTimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.HasKey("LeadslyTimeZoneId");

                    b.HasIndex("TimeZoneId")
                        .IsUnique();

                    b.ToTable("SupportedTimeZones");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.OrphanedCloudResource", b =>
                {
                    b.Property<string>("OrphanedCloudResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Arn")
                        .HasColumnType("text");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("OrphanedCloudResourceId");

                    b.ToTable("OrphanedCloudResources");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.SocialAccount", b =>
                {
                    b.Property<string>("SocialAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("HalUnitId")
                        .HasColumnType("text");

                    b.Property<bool>("Linked")
                        .HasColumnType("boolean");

                    b.Property<bool>("MonthlySearchLimitReached")
                        .HasColumnType("boolean");

                    b.Property<bool>("RunProspectListFirst")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirtualAssistantId")
                        .HasColumnType("text");

                    b.HasKey("SocialAccountId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("HalUnitId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("VirtualAssistantId")
                        .IsUnique();

                    b.ToTable("SocialAccounts");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.VirtualAssistant", b =>
                {
                    b.Property<string>("VirtualAssistantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HalUnitId")
                        .HasColumnType("text");

                    b.HasKey("VirtualAssistantId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("HalUnitId");

                    b.ToTable("VirtualAssistants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Customer_Stripe", "Customer_Stripe")
                        .WithMany()
                        .HasForeignKey("Customer_StripeId");

                    b.Navigation("Customer_Stripe");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Campaign", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("Campaigns")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", "CampaignProspectList")
                        .WithMany()
                        .HasForeignKey("CampaignProspectListId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("CampaignProspectList");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspect", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", "CampaignProspectList")
                        .WithMany("CampaignProspects")
                        .HasForeignKey("CampaignProspectListId");

                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspect", "PrimaryProspect")
                        .WithMany()
                        .HasForeignKey("PrimaryProspectId");

                    b.Navigation("Campaign");

                    b.Navigation("CampaignProspectList");

                    b.Navigation("PrimaryProspect");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectFollowUpMessage", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspect", "CampaignProspect")
                        .WithMany("FollowUpMessages")
                        .HasForeignKey("CampaignProspectId");

                    b.Navigation("CampaignProspect");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", "PrimaryProspectList")
                        .WithMany()
                        .HasForeignKey("PrimaryProspectListId");

                    b.Navigation("PrimaryProspectList");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignWarmUp", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessage", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany("FollowUpMessages")
                        .HasForeignKey("CampaignId");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessageDelay", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessage", "FollowUpMessage")
                        .WithOne("Delay")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessageDelay", "FollowUpMessageId");

                    b.Navigation("FollowUpMessage");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ConnectionWithdrawPhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.SocialAccount", "SocialAccount")
                        .WithOne("ConnectionWithdrawPhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.ConnectionWithdrawPhase", "SocialAccountId");

                    b.Navigation("SocialAccount");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.FollowUpMessagePhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithOne("FollowUpMessagePhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.FollowUpMessagePhase", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.MonitorForNewConnectionsPhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.SocialAccount", "SocialAccount")
                        .WithOne("MonitorForNewProspectsPhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.MonitorForNewConnectionsPhase", "SocialAccountId");

                    b.Navigation("SocialAccount");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ProspectListPhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithOne("ProspectListPhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.ProspectListPhase", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.ScanProspectsForRepliesPhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.SocialAccount", "SocialAccount")
                        .WithOne("ScanProspectsForRepliesPhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.ScanProspectsForRepliesPhase", "SocialAccountId");

                    b.Navigation("SocialAccount");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendConnectionRequestPhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithOne("SendConnectionRequestPhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendConnectionRequestPhase", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendEmailInvitePhase", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithOne("SendEmailInvitePhase")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.Campaigns.Phases.SendEmailInvitePhase", "CampaignId");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspect", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", "PrimaryProspectList")
                        .WithMany("PrimaryProspects")
                        .HasForeignKey("PrimaryProspectListId");

                    b.Navigation("PrimaryProspectList");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", "User")
                        .WithMany("ProspectLists")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrl", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", null)
                        .WithMany("SearchUrls")
                        .HasForeignKey("CampaignProspectListId");

                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", "PrimaryProspectList")
                        .WithMany("SearchUrls")
                        .HasForeignKey("PrimaryProspectListId");

                    b.Navigation("PrimaryProspectList");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrlDetails", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany("SentConnectionsStatuses")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SearchUrlProgress", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany("SearchUrlsProgress")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.SendConnectionsStage", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.Campaigns.Campaign", "Campaign")
                        .WithMany("SendConnectionStages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.CloudMapDiscoveryService", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.EcsService", "EcsService")
                        .WithOne("CloudMapDiscoveryService")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.CloudMapDiscoveryService", "EcsServiceId");

                    b.HasOne("Leadsly.Domain.Models.Entities.VirtualAssistant", null)
                        .WithMany("CloudMapDiscoveryServices")
                        .HasForeignKey("VirtualAssistantId");

                    b.Navigation("EcsService");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsService", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.VirtualAssistant", null)
                        .WithMany("EcsServices")
                        .HasForeignKey("VirtualAssistantId");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsServiceRegistry", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.EcsService", "EcsService")
                        .WithMany("EcsServiceRegistries")
                        .HasForeignKey("EcsServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EcsService");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsTask", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.EcsService", "EcsService")
                        .WithMany("EcsTasks")
                        .HasForeignKey("EcsServiceId");

                    b.Navigation("EcsService");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsTaskDefinition", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.VirtualAssistant", null)
                        .WithMany("EcsTaskDefinitions")
                        .HasForeignKey("VirtualAssistantId");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.HalUnit", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("HalDetails")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.SocialAccount", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany("SocialAccounts")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Leadsly.Domain.Models.Entities.HalUnit", "HalDetails")
                        .WithOne("SocialAccount")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.SocialAccount", "HalUnitId");

                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leadsly.Domain.Models.Entities.VirtualAssistant", "VirtualAssistant")
                        .WithOne("SocialAccount")
                        .HasForeignKey("Leadsly.Domain.Models.Entities.SocialAccount", "VirtualAssistantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HalDetails");

                    b.Navigation("User");

                    b.Navigation("VirtualAssistant");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.VirtualAssistant", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("VirtualAssistants")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leadsly.Domain.Models.Entities.HalUnit", "HalUnit")
                        .WithMany()
                        .HasForeignKey("HalUnitId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("HalUnit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Leadsly.Domain.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("HalDetails");

                    b.Navigation("ProspectLists");

                    b.Navigation("SocialAccounts");

                    b.Navigation("VirtualAssistants");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.Campaign", b =>
                {
                    b.Navigation("FollowUpMessagePhase");

                    b.Navigation("FollowUpMessages");

                    b.Navigation("ProspectListPhase");

                    b.Navigation("SearchUrlsProgress");

                    b.Navigation("SendConnectionRequestPhase");

                    b.Navigation("SendConnectionStages");

                    b.Navigation("SendEmailInvitePhase");

                    b.Navigation("SentConnectionsStatuses");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspect", b =>
                {
                    b.Navigation("FollowUpMessages");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.CampaignProspectList", b =>
                {
                    b.Navigation("CampaignProspects");

                    b.Navigation("SearchUrls");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.FollowUpMessage", b =>
                {
                    b.Navigation("Delay");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.Campaigns.PrimaryProspectList", b =>
                {
                    b.Navigation("PrimaryProspects");

                    b.Navigation("SearchUrls");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.EcsService", b =>
                {
                    b.Navigation("CloudMapDiscoveryService");

                    b.Navigation("EcsServiceRegistries");

                    b.Navigation("EcsTasks");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.HalUnit", b =>
                {
                    b.Navigation("SocialAccount");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.SocialAccount", b =>
                {
                    b.Navigation("ConnectionWithdrawPhase");

                    b.Navigation("MonitorForNewProspectsPhase");

                    b.Navigation("ScanProspectsForRepliesPhase");
                });

            modelBuilder.Entity("Leadsly.Domain.Models.Entities.VirtualAssistant", b =>
                {
                    b.Navigation("CloudMapDiscoveryServices");

                    b.Navigation("EcsServices");

                    b.Navigation("EcsTaskDefinitions");

                    b.Navigation("SocialAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
